### ISSUE TITLE
Flakey unit test

### ISSUE THREAD

**Issue by lucas42** [lucas42/lucos_media_manager#21]
Sometimes `PlaylistTest:topups()` fails on: https://github.com/lucas42/lucos_media_manager/blob/2230552d5d463dbb879113dc54319b7e5ec4199f/src/test/java/PlaylistTest.java#L73 

Example failure: https://app.circleci.com/pipelines/github/lucas42/lucos_media_manager/69/workflows/6dffe309-ab53-4cf4-bddd-f3d519ea57aa/jobs/188

```
13.26 [ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.24 s <<< FAILURE! - in PlaylistTest
13.26 [ERROR] topups  Time elapsed: 0.067 s  <<< FAILURE!
13.26 org.mockito.exceptions.verification.TooFewActualInvocations: 
13.26 
13.26 loganne.post(
13.26     "fetchTracks",
13.26     "Fetching more tracks to add to the current playlist"
13.26 );
13.26 Wanted 2 times:
13.26 -> at Loganne.post(Loganne.java:18)
13.26 But was 1 time:
13.26 -> at Playlist.topupTracks(Playlist.java:120)
13.26 
13.26   at PlaylistTest.topups(PlaylistTest.java:73)
13.26 
```

**Comment by lucas42** [comment]
Haven't had any issue with this one since the order was swapped.  Going to assume it's fixed somehow.
