### ISSUE TITLE
Can't recover from null pointer exception

### ISSUE THREAD

**Issue by lucas42** [lucas42/lucos_media_manager#3]
The follow stracktrace occurs sometimes:
```
Feb 18 19:07:23 lucos_media_manager[21825]: Server Error (HttpRequest, host:10.0.0.4):
Feb 18 19:07:23 lucos_media_manager[21825]: java.lang.NullPointerException
Feb 18 19:07:23 lucos_media_manager[21825]: at java.util.LinkedList$ListItr.next(LinkedList.java:893)
Feb 18 19:07:23 lucos_media_manager[21825]: at Manager.createFullSummary(Manager.java:165)
Feb 18 19:07:23 lucos_media_manager[21825]: at Manager.fullSummaryHasChanged(Manager.java:101)
Feb 18 19:07:23 lucos_media_manager[21825]: at HttpRequest.processRequest(HttpRequest.java:181)
Feb 18 19:07:23 lucos_media_manager[21825]: at HttpRequest.run(HttpRequest.java:30)
Feb 18 19:07:23 lucos_media_manager[21825]: at java.lang.Thread.run(Thread.java:745)
```
Once it starts it occurs repetitively.  Only way to fix it is restart the service.

**Comment by lucas42** [comment]
This stacktrace, and even the function mentioned, no longer exists.
Create new issue if it reoccurs in future.
