### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by lucas42** [lucas42/lucos_media_manager#34]
Stacktrace:
```
ERROR: Unknown Error (HttpRequest, host:172.25.0.1):
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.base/java.util.LinkedList.checkPositionIndex(LinkedList.java:564)
	at java.base/java.util.LinkedList.listIterator(LinkedList.java:871)
	at java.base/java.util.AbstractList.listIterator(AbstractList.java:311)
	at java.base/java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:238)
	at java.base/java.util.AbstractList.hashCode(AbstractList.java:566)
	at Playlist.hashCode(Playlist.java:117)
	at Status.hashCode(Status.java:37)
	at Status.summaryHasChanged(Status.java:44)
	at FrontController.respond(FrontController.java:61)
	at FrontController.processRequest(FrontController.java:46)
	at FrontController.run(FrontController.java:26)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lucas42** [comment]
Haven't noticed this in a while, so closing for now.
